version: "3"

services:
  daemon:
    build:
      context: .
      dockerfile: ./daemon.dockerfile
    image: tracedaemon
    network_mode: "host"
    restart: always
    volumes:
      - ./bin:/opt/traced/bin
      - ./config:/opt/traced/config
      - ./logs:/opt/traced/logs
      - ./shell:/opt/traced/shell

  demo:
    build:
      context: .
      dockerfile: ./demo.dockerfile
    image: tracedemo
    network_mode: "host"
    volumes:
      - ./bin:/opt/demo/traceID/bin
      - ./config:/opt/demo/traceID/config
      - ./logs:/opt/demo/traceID/logs
      - ./shell:/opt/demo/traceID/shell
